import type { PropertyCharacterizationData } from './matrix-types';

export const MAIN_E2E_SCENARIOS: readonly PropertyCharacterizationData[] = [
  {
    id: 'CALC-ROOF-001',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PRIVATE_HOUSE',
    polygons: ['building'],
    roofSurfaces: ['concrete'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-002',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PRIVATE_HOUSE',
    polygons: ['building'],
    roofSurfaces: ['tiles'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-003',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PRIVATE_HOUSE',
    polygons: ['building'],
    roofSurfaces: ['iscoverit'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-004',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['concrete'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-005',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['tiles'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-006',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['iscoverit'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-007',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_COMMERCIAL',
    polygons: ['building'],
    roofSurfaces: ['concrete', 'iscoverit'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-008',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_AGRICULTURAL',
    polygons: ['building'],
    roofSurfaces: ['iscoverit'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'continue according to persona after funding',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-009',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_AGRICULTURAL',
    polygons: ['building', 'sports-court'],
    roofSurfaces: ['iscoverit', 'sports-court'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'mark building only; sports court is calculated as fully marked',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: true,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-010',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PUBLIC',
    polygons: ['sports-court'],
    roofSurfaces: ['sports-court'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'skip object and roof marking steps; continue according to persona',
    skipsObjectAndRoofSteps: true,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-011',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PUBLIC',
    polygons: ['parking'],
    roofSurfaces: ['parking'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'skip object and roof marking steps; continue according to persona',
    skipsObjectAndRoofSteps: true,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
  {
    id: 'CALC-ROOF-012',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_PUBLIC',
    polygons: ['building', 'parking', 'sports-court'],
    roofSurfaces: ['iscoverit', 'parking', 'sports-court'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior: 'mark building only; parking and sports court are calculated as fully marked',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: true,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
] as const;

export const NEGATIVE_PANEL_SCENARIOS: readonly PropertyCharacterizationData[] = [
  {
    id: 'CALC-ROOF-021',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['concrete'],
    panelMode: 'below-minimum',
    minimumPanelCount: 4,
    wantFinancingOffer: false,
    expectedBehavior: 'show insufficient panels modal and do not create quotations',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
] as const;

export const UI_ONLY_SCENARIOS: readonly PropertyCharacterizationData[] = [
  {
    id: 'CALC-ROOF-022',
    arenaType: 'ARENA_TYPE_MAIN',
    address: 'HaBarzel 32, Tel Aviv-Yafo',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['concrete'],
    panelMode: 'none',
    minimumPanelCount: 0,
    wantFinancingOffer: false,
    expectedBehavior: 'no API/JSON scenario; request is not sent without panel marking',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
] as const;

export const RAMOT_SCENARIOS: readonly PropertyCharacterizationData[] = [
  {
    id: 'RAMOT-001',
    arenaType: 'ARENA_TYPE_RAMOT',
    address: 'Ramot, Jerusalem',
    propertyType: 'PROPERTY_TYPE_BUILDING',
    polygons: ['building'],
    roofSurfaces: ['concrete'],
    panelMode: 'quotable',
    minimumPanelCount: 5,
    wantFinancingOffer: false,
    expectedBehavior:
      'customer reaches pre-characterized quotations or submits a characterization request; consultant characterizes properties',
    skipsObjectAndRoofSteps: false,
    onlyBuildingAreaCanBeMarked: false,
    roofState: {},
    roofObjects: {},
    roofLevels: {},
  },
] as const;

export const LEGACY_MAIN_PROPERTY_CHARACTERIZATION: PropertyCharacterizationData = {
  id: 'LEGACY-MAIN',
  arenaType: 'ARENA_TYPE_MAIN',
  address: 'HaBarzel 32, Tel Aviv-Yafo',
  propertyType: 'PROPERTY_TYPE_COMMERCIAL',
  polygons: ['building'],
  roofSurfaces: ['concrete'],
  panelMode: 'quotable',
  minimumPanelCount: 5,
  wantFinancingOffer: false,
  expectedBehavior: 'legacy single scenario',
  skipsObjectAndRoofSteps: false,
  onlyBuildingAreaCanBeMarked: false,
  roofState: {},
  roofObjects: {},
  roofLevels: {},
};
